[package]
name = "save_to_disk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
livekit = { path = "../../livekit", version = "0.3.2" }
bytes = "1.4.0"
tokio-util = "0.7.8"
futures = "0.3.28"
