[package]
name = "save_to_disk"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["full"] }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
bytes = { workspace = true }
futures = "0.3.28"
