[package]
name = "screensharing"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["full"] }
env_logger = { workspace = true }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
livekit-api = { workspace = true }
log = { workspace = true }
clap = { workspace = true, features = ["derive"] }
