[package]
name = "livekit-datatrack"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/livekit/rust-sdks"
readme = "README.md"

[dependencies]
dashmap = "6.1.0"
livekit-protocol = { workspace = true }
log = "0.4.28"
thiserror = "2.0.17"
tokio = { version = "1.48.0", default-features = false, features = ["sync"] }
