headerPath = "Apache-2.0.txt"
excludes = [
    "yuv-sys/libyuv",
    "soxr-sys/src",
    "webrtc-sys/libwebrtc",
    "webrtc-sys/test",
    "webrtc-sys/src/lazy_load_deps_for",
    "webrtc-sys/src/vaapi",
    "webrtc-sys/src/nvidia",
    "webrtc-sys/.clang-format",
    "livekit-protocol/protocol",
    "livekit-ffi/.cargo/config",
    "examples",
    "NOTICE",
    ".github",
    "*.toml",
    "!Makefile.toml",
    "*.txt",
    # Generated files
    "livekit-protocol/src/livekit.rs",
    "livekit-protocol/src/livekit.serde.rs",
    "livekit-uniffi/*_test",
    "livekit-uniffi/support",
    "livekit-ffi-node-bindings/src/napi/native.cjs",
    "livekit-ffi-node-bindings/src/napi/native.d.ts",
    "livekit-ffi-node-bindings/src/napi/native.js",
]

[mapping.DOUBLESLASH_STYLE]
extensions = ["proto", "ts", "js", "cjs"]

[mapping.SLASHSTAR_STYLE]
extensions = ["mm"]

[properties]
inceptionYear = 2025
copyrightOwner = "LiveKit, Inc."
projectName = "LiveKit Rust SDKs"
