[package]
name = "local_audio"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["full"] }
env_logger = { workspace = true }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
livekit-api = { workspace = true, features = ["rustls-tls-native-roots"] }
libwebrtc = { workspace = true }
log = { workspace = true }
cpal = "0.15"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
futures-util = "0.3"
