[package]
name = "imgproc"
version = "0.3.14"
edition = "2021"
authors = ["Theo Monnom <theo.8bits@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "image processing library"

[dependencies]
yuv-sys = { workspace = true }
