[package]
name = "send_bytes"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["full"] }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
log = { workspace = true }
env_logger = { workspace = true }
bitfield-struct = "0.11.0"
rand = { workspace = true }
colored = "3.0.0"
