[package]
name = "soxr-sys"
version = "0.1.2"
authors = ["Theo Monnom <theo.8bits@gmail.com"]
edition.workspace = true
license.workspace = true
description = "libsoxr bindings"

[dependencies]


[build-dependencies]
cc = "1.0"

[dev-dependencies]
hound = "3.4"
