[package]
name = "soxr-sys"
version = "0.1.1"
authors = ["Theo Monnom <theo.8bits@gmail.com"]
edition = "2021"
license = "Apache-2.0"
description = "libsoxr bindings"

[dependencies]


[build-dependencies]
cc = "1.0"

[dev-dependencies]
hound = "3.4"
