[package]
name = "basic_room_async"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.0"
async-std = "1"
env_logger = "0.10"
livekit = { path = "../../livekit", version = "0.3.0", default-features = false, features = ["native-tls", "async"]}
livekit-api = { path = "../../livekit-api", version = "0.3.0"}
log = "0.4"

[workspace]