[package]
name = "encoded_video"
version = "0.1.0"
edition.workspace = true
publish = false

[[bin]]
name = "encoded_video"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true, features = ["full", "parking_lot"] }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
libwebrtc = { workspace = true }
livekit-api = { workspace = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
