[package]
name = "play_from_disk"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
tokio = { version = "1", features = ["full"] }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
thiserror = "1.0.47"
log = "0.4.20"
env_logger = { workspace = true }
