[package]
name = "basic_text_stream"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
futures-util = { version = "0.3", default-features = false, features = ["sink"] }
livekit = { path = "../../livekit" }
log = "0.4.26"
env_logger = "0.11.7"

[workspace]