[package]
name = "simple_room"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
livekit = { path = "../../livekit", version = "0.1.1" }
futures = "0.3"
wgpu = "0.16"
winit = "0.28"
parking_lot = "0.12.1"

egui = { git = "https://github.com/emilk/egui" }
egui-wgpu = { git = "https://github.com/emilk/egui", features = ["winit"] }
egui-winit = { git = "https://github.com/emilk/egui" }

image = "0.24"
