[package]
name = "encrypted_text_stream"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
tokio = { workspace = true, features = ["full"] }
futures-util = { workspace = true, default-features = false, features = ["sink"] }
livekit = { workspace = true, features = ["rustls-tls-native-roots"] }
livekit-api = { workspace = true, features = ["rustls-tls-native-roots"] }
log = { workspace = true }
env_logger = { workspace = true }
